name: Build and Publish bahmni-offline
on:
  push:
    branches:
      - master
      - 'release-*'
      - BAH-2334
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    
  repository_dispatch:
    types: ['bahmni-connect-trigger', 'bahmni-offline-sync-trigger']

    paths-ignore:
      - '**.md'

jobs:
  rpm-build-publish:
    name: RPM Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set artifact version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - name: Download bahmni-connect-apps
        run: sh .github/download_artifact.sh bahmni-connect bahmni-connect-apps-zip ${{secrets.BAHMNI_PAT}}

      - name: Download bahmni-offline-sync omod
        run: sh .github/download_artifact.sh bahmni-offline-sync bahmni-offline-sync-omod ${{secrets.BAHMNI_PAT}}
      - name: Setup Java 8 for Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Gradle Build
        run: |
            ls package/rpm/resources/
            cd package/rpm
            export version=$(awk -F- '{print $1}' <<< ${{env.ARTIFACT_VERSION}})
            export release=$(awk -F- '{print $2}' <<< ${{env.ARTIFACT_VERSION}})
            ./gradlew -Pversion=$version -Prelease=$release clean buildRpm
      - uses: actions/upload-artifact@v3
        with:
          name: bahmni-offline-rpm
          path: package/rpm/build/distributions/*.rpm
    