name: Build and Publish bahmni-offline
on:
  push:
    branches:
      - master
      - 'release-*'
      - BAH-2334
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'

jobs:
  build-bahmni-connect:
    name: Build bahmni-connect
    runs-on: ubuntu-latest
    steps:
      - name: Check out bahmni-connect
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-connect
          ref: master
          # path: bahmni-connect
          persist-credentials: false
      - run: echo "showing checkout done or not" && ls
      - name: Setup Node
        uses: actions/setup-node@v1
      - run: npm install -g yarn
      - run: sudo gem install compass
      - run: cd ui && scripts/package.sh
      - name: Upload apps.zip as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-connect-apps
          path: | 
            ui/bahmni-connect-apps
      - name: Upload androidDist as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-android
          path: | 
            ui/androidDist

  # rpm-build-publish:
  #   name: RPM Build and Publish
  #   runs-on: ubuntu-latest
  #   needs: [ build ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set artifact version
  #       run: |
  #         wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
  #         ./setArtifactVersion.sh
  #         rm setArtifactVersion.sh
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: openelis.war
  #         path: package/resources/
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: openelis.zip
  #         path: package/resources/
  #     - name: Download bahmni-embedded-tomcat.zip
  #       run: sh .github/download_artifact.sh bahmni-package bahmni-embedded-tomcat ${{secrets.BAHMNI_PAT}}
  #     - name: Download openelis_backup.sql.gz file from emr-functional-tests/dbdump
  #       run:  |
  #             wget https://raw.githubusercontent.com/Bahmni/emr-functional-tests/master/dbdump/openelis_backup.sql.gz 
  #             gunzip -c openelis_backup.sql.gz > package/resources/openelis_demo_dump.sql
  #     - name: Generate bahmni_openelis_revision.json
  #       run: ./package/rpm/test/bahmni_openelis_revision.sh > bahmni_openelis_revision.json
  #     - name: Setup Java 8 for Gradle
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'zulu'
  #         java-version: '8'
  #     - name: Gradle Build
  #       run: |
  #           cd package/rpm
  #           export version=$(awk -F- '{print $1}' <<< ${{env.ARTIFACT_VERSION}})
  #           export release=$(awk -F- '{print $2}' <<< ${{env.ARTIFACT_VERSION}})
  #           ./gradlew -Pversion=$version -Prelease=$release clean buildRpm
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: bahmni-lab-rpm
  #         path: package/rpm/build/distributions/*.rpm
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: openelis-revision
  #         path: bahmni_openelis_revision.json