name: Build and Publish bahmni-offline
on:
  push:
    branches:
      - master
      - 'release-*'
      - BAH-2334
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'

jobs:
  build-bahmni-connect:
    name: Build bahmni-connect
    runs-on: ubuntu-latest
    steps:
      - name: Check out bahmni-connect
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-connect
          ref: master
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v1
      - run: npm install -g yarn
      - run: sudo gem install compass
      - run: cd ui && scripts/package.sh
      - run: zip -r bahmni-connect-apps.zip ui/bahmni-connect-apps
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-connect-apps
          path: | 
            bahmni-connect-apps.zip
      - name: Upload androidDist as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-android
          path: | 
            ui/androidDist

  # build-bahmni-offlinesync:
  #   name: Build bahmni-offlinesync
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out bahmni-offline-sync
  #       uses: actions/checkout@v2
  #       with:
  #         repository: Bahmni/bahmni-offline-sync
  #         ref: master
  #         persist-credentials: false
  #     - name: Setup Java 8
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: 'zulu'
  #         java-version: '8'      
  #     - run: mvn clean install -U -PIT -DskipTests
  #     - name: rename the omod
  #       run: mv omod/target/bahmniOfflineSync*.omod omod/target/bahmniOfflineSync.omod
  #     - name: Upload bahmniOfflineSync as Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: bahmni-offline-sync
  #         path: | 
  #           omod/target/bahmniOfflineSync.omod

  rpm-build-publish:
    name: RPM Build and Publish
    runs-on: ubuntu-latest
    needs: [ build-bahmni-connect] #build-bahmni-offlinesync
    steps:
      - uses: actions/checkout@v2
      - name: Set artifact version
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          rm setArtifactVersion.sh
      - uses: actions/download-artifact@v3
        with:
          name: bahmni-connect-apps
          path: package/rpm/resources/
      - run: |
          ls package/rpm/resources/
      #     zip -r package/rpm/resources/bahmni-connect-apps.zip package/rpm/resources/bahmni-connect-apps
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: bahmni-offline-sync
      #     path: package/rpm/resources/
      - name: Setup Java 8 for Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Gradle Build
        run: |
            cd package/rpm
            export version=$(awk -F- '{print $1}' <<< ${{env.ARTIFACT_VERSION}})
            export release=$(awk -F- '{print $2}' <<< ${{env.ARTIFACT_VERSION}})
            ./gradlew -Pversion=$version -Prelease=$release clean buildRpm
      - uses: actions/upload-artifact@v3
        with:
          name: bahmni-offline-rpm
          path: package/rpm/build/distributions/*.rpm